Hw06 testing
sergeyyarin/otus_go_basic pull request #7
Opened 2023-12-11 19:15 UTC by sergeyyarin

## Домашнее задание №6 «Покрыть тестами предыдущие задания»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 4 баллов

2023-12-11 20:59 UTC, vladislavmass requested changes
Хорошее начало, но нет тестов для 2 дз

2023-12-15 11:52 UTC, sergeyyarin commented on hw06_testing/jsonapp_test.go
> +				require.Contains(t, err.Error(), "no such file or directory")
@vladislavmass Владислав, я здесь хотел с помощью require.ErrorAs сравнить ошибку с типом os.PathError. Так и не понял почему не получается, объясните пожалуйста как тут правильно поступить?

2023-12-15 12:33 UTC, vladislavmass approved these changes

2023-12-15 12:33 UTC, vladislavmass commented on hw06_testing/jsonapp/printer/pkg.go
> +func PrintStaff(staff []types.Employee) string {
Красивым вариантом было бы передать сюда еще и интерфейс io.Writer. таким образом мы бы написали тест, сохранив первоначальную функциональность

2023-12-15 12:33 UTC, vladislavmass commented on hw06_testing/jsonapp/reader/pkg.go
> +func ReadJSON(filePath string) ([]types.Employee, error) {
В этот метод было бы лучше передать интерфейс io.Reader и читать из него.

2023-12-15 13:17 UTC, merged